---
# tasks file for environment
- name: save variable settings in /etc/environment
  lineinfile:
    path: /etc/environment
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}="{{ item.value }}"'
  loop: "{{ environment_list | dict2items }}"
